ALTER TABLE `StockMove`
  MODIFY `type` ENUM(
    'SALE_RESERVE',
    'SALE_UNRESERVE',
    'SALE_DELIVERY',
    'CUSTOMER_RETURN',
    'PURCHASE_RECEIPT',
    'SUPPLIER_RETURN',
    'MO_COMPONENT_RESERVE',
    'MO_COMPONENT_UNRESERVE',
    'MO_COMPONENT_CONSUME',
    'MO_FINISHED_PRODUCE',
    'INTERNAL_TRANSFER',
    'STOCK_ADJUSTMENT_IN',
    'STOCK_ADJUSTMENT_OUT',
    'SCRAP',
    'REVERSAL',
    'ADJUSTMENT',
    'RESERVATION_RELEASE',
    'PROCUREMENT_CREATED'
  ) NOT NULL;
